### ISSUE TITLE
jenkins-x installation never succeed on local Kubernetes 1.10 cluster!

### ISSUE THREAD

**Issue by dongdan39** [jenkins-x/jenkins-x-platform#1451]
Hi, 
   When I tried to install jenkins-x on my local Kubernetes 1.10 cluster, it never succeeds! 
On the master node of the kubernetes cluster:

#helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
 Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

#jx install --ingress-namespace kube-system
....
 helm install jenkins-x/jenkins-x-platform --name jenkins-x -f ./myvalues.yaml -f ./secrets.yaml --version 0.0.1129 --values=/root/.jx/gitSecrets.yaml --values=/root/.jx/adminSecrets.yaml --values=/root/.jx/extraValues.yaml --namespace=jx --timeout=6000
 Error: a release named jenkins-x already exists.
 Run: helm ls --all jenkins-x; to check the status of the release
 Or run: helm del --purge jenkins-x; to delete it
 make: *** [install] 错误 1
 Error: Command failed make ARGS=--values=/root/.jx/gitSecrets.yaml --values=/root/.jx/adminSecrets.yaml --values=/root/.jx/extraValues.yaml --namespace=jx --timeout=6000 install
 error: exit status 2

#helm ls --all jenkins-x
NAME REVISION UPDATED STATUS CHART NAMESPACE
 jenkins-x 1 Thu May 31 01:07:34 2018 FAILED jenkins-x-platform-0.0.1129 jx

How the persistent volume is handled in the default installing command(jx install)? Is it possible to use NFS for this storage and how to set it up in the "jx install" or helm command? Thanks!

#helm del --purge jenkins-x
Error: timed out waiting for the condition

Cheers,
Dan

**Comment by dongdan39** [comment]
Hi, 
  Found the installation is stuck in creating of PersistentVolume for jenkins, jenkins-x-chartmuseum, jenkins-x-docker-registry etc. So how the default "jx install" will handle the PV/PVC in installation on local Kubenetes cluster? Seems it will defenitely fail forever! Did anybody ever succeed in jenkins-x installation on such local Kubernetes cluster? 

Cheers,
Dan

**Comment by isaron** [comment]
@dongdan39 
Before deploy jx, 
1. set up local or share storage for k8s' PV/PVC, such as GlusterFS, Ceiph. 
2. deploy client for k8s.
My choice is NFS, and client from https://github.com/kubernetes-incubator/external-storage/nfs-client.

This could be helpful.
