### ISSUE TITLE
specifying maven settings-security.xml at install not currently supported

### ISSUE THREAD

**Issue by ryandawsonuk** [jenkins-x/jenkins-x-platform#3413]
Currently you can set a settings.xml file to be loaded into build pods. The file is loaded into the secret via helm property:

https://github.com/jenkins-x/jenkins-x-platform/blob/1e45247339d4bb91ced584cd501719174a4a8aa2/templates/maven-settings-secret.yaml

Which we could configure at install time - https://github.com/jenkins-x/cloud-environments/blob/master/env-jx-infra/secrets.yaml#L25

But for the nexus we want to use we also need a settings-security.xml. This is because we have a password in the settings.xml that is [encrypted against a master password](https://maven.apache.org/guides/mini/guide-encryption.html) in the settings-security.xml file. 

Could we have a PipelineSecrets.SettingsSecurityXML in addition to PipelineSecrets. MavenSettingsXML? It would just need to be mounted into the same maven-settings-secret.yaml file as both files should be mounted in the same directory (I've tried manually deleting and recreating the secret and that works for me but it doesn't let me set it at the point of install).

**Comment by jglick** [comment]
Possibly subsumed by #4806 if implemented.
