### ISSUE TITLE
Jenkins chart museum is down from last 2 hour

### ISSUE THREAD

**Issue by ysaakpr** [jenkins-x/jenkins-x-platform#4408]
https://chartmuseum.build.cd.jenkins-x.io/ should be highly available, because the entire deployment process is braking if the Jenkins chart museum goes offline, because of the expose controller dependancy.
<img width="1680" alt="screen shot 2018-12-04 at 1 44 27 pm" src="https://user-images.githubusercontent.com/20730186/49427995-d7c0ee80-f7ca-11e8-9a0b-aa2a7ab939ac.png">

**Comment by ysaakpr** [comment]
<img width="1315" alt="screen shot 2018-12-04 at 1 47 02 pm" src="https://user-images.githubusercontent.com/20730186/49428082-2078a780-f7cb-11e8-86cc-7d50286c99cb.png">

**Comment by pmuir** [comment]
We have a HA chartmuseum at http://chartmuseum.jenkins-x.io. You should
upgrade the platform `jx upgrade platform`, the CLI `jx upgrade cli` and
the build templates (if using serverless `jx upgrade addon
jx-build-templates`)
