### ISSUE TITLE
Support Adding annotations onto pod templates

### ISSUE THREAD

**Issue by jecafarelli** [jenkins-x/jenkins-x-platform#4513]
Add the ability to pass in a list of annotations for a pod template to support k2iam and Kiam annotations on certain templates.

**Comment by jecafarelli** [comment]
Added a first commit to this, but I am not sure how or where during the chart apply does it take the pod template config map and update the server configmap with this information. Its not updating the annotation section of the server configmap, so im guessing there is still a spot somewhere that needs to grab the pod template configmap for annotation and add it into the server config.

**Comment by jecafarelli** [comment]
Ok so I have found the missing puzzle piece. If I unpack the jenkins chart that gets downloaded from http://chartmuseum.jenkins-x.io I can see the config.yml has those settings in them that I need to change to get this to work, unfortunately I cant seem to find the matching chart code in github anywhere.

I took a look for the code [here](https://github.com/helm/charts/blob/master/stable/jenkins/templates/config.yaml) but it doesnt match what was unpacked from that chart. 

still kind of new to this code base so Im not sure where this code would be. @jstrachan Could you point me in the direction to where I can find the yaml files for the jenkins chart used in jx?

**Comment by rawlingsj** [comment]
Ah yes so we ought to split this out into our https://github.com/jenkins-x-charts org but for now we use a fork here https://github.com/jenkins-x/charts/blob/jenkins/stable/jenkins/templates/config.yaml
