### ISSUE TITLE
Unable to log in to Jenkins Console after a fresh install

### ISSUE THREAD

**Issue by elarbi** [jenkins-x/jenkins-x-platform#4791]
Hello,

I've a launched this JX install:
`jx create cluster gke --git-private --gitops --git-api-token xyxyxyxyx --git-provider-kind bitbucketcloud --git-provider-url https://bitbucket.org --git-username usernamexxx `

At the end the script prints a way to get my admin password from Vault:
eval `jx get vault-config` && vault kv get secret/admin/jenkins

So I tried and get my password:
====== Data ======
Key         Value
---         -----
Password    en!BaFakePassword
Username    admin

**But when I go to my Jenkins console (using jx console) I get an error: "Invalid username or password"**

**Comment by elarbi** [comment]
When I check **jenkinsAuth.yaml** I found:
servers: []
defaultusername: ""
currentserver: ""
pipelineusername: ""
pipelineserver: ""

**Comment by elarbi** [comment]
Ok I've found the issue !
I used KSD as stated here: https://jenkins-x.io/faq/issues/#how-do-i-get-the-password-and-username-for-jenkins

I found that my password is "admin" and not the one stored in Vault.
So it's not coherent with: https://jenkins-x.io/faq/issues/#how-do-i-get-the-password-and-username-for-jenkins

**Comment by fluxens** [comment]
Same problem here. the decoded jenkins-admin-password is not accepted. 'admin' is also not working for me
@elarbi how did you find out it was admin for you?
