### ISSUE TITLE
release: "jenkins-x" not found'

### ISSUE THREAD

**Issue by mcgonagle** [jenkins-x/jenkins-x-platform#5240]
I am trying to install Jenkins-X via the google cloud shell, and am running into a problem with the following error: 
error creating cluster installing the Jenkins X platform: failed to install/upgrade the jenkins-x platform chart: failed to run 'helm upgrade --namespace jx --install --timeout 6000 --version 0.0.3832 --values /home/tmcgonagle/.jx/cloud-environments/env-gke/myvalues.yaml --values /home/tmcgonagle/.jx/adminSecrets.yaml --values /home/tmcgonagle/.jx/extraValues.yaml --values /home/tmcgonagle/.jx/cloud-environments/env-gke/secrets.yaml jenkins-x jenkins-x/jenkins-x-platform' command in directory '', output: 'Release "jenkins-x" does not exist. Installing it now.
NAME:   jenkins-x
Error: getting deployed release "jenkins-x": release: "jenkins-x" not found'

**Comment by krishnakumar6893** [comment]
@mcgonagle Refer this thread https://github.com/jenkins-x/jx/issues/3574
