### ISSUE TITLE
Can not access "Manage Jenkins"

### ISSUE THREAD

**Issue by sanigo** [jenkins-x/jenkins-x-platform#5294]
I believe it is concerned with the locale plugin, it is ok in English, but broken in Chinese locale.
It is the latest version: v2.0.80.
> Stack trace
> org.apache.commons.jelly.JellyTagException: jar:file:/var/jenkins_home/war/WEB-INF/lib/jenkins-core-2.150.3.jar!/hudson/model/UpdateCenter/CoreUpdateMonitor/message.jelly:53:20: <j:otherwise> can't parse argument number: changelog.url
> 	at org.apache.commons.jelly.impl.TagScript.handleException(TagScript.java:726)
> 	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:281)
> 	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
> 	at org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:161)
> 	at org.apache.commons.jelly.tags.core.ChooseTag.doTag(ChooseTag.java:38)
> 	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
> 	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)

**Comment by bamboox** [comment]
Having the same issue
