### ISSUE TITLE
Helm & Ansible playbook?

### ISSUE THREAD

**Issue by LD-Oteemo** [jenkins-x/jenkins-x-platform#5390]
I am trying to setup jenkins-x...

I'm using helm, and I want to be able to install using ansible... but I can't seem to find a working tutorial for it, or even a set of helm charts with playbooks that I can work from. I looked in the jenkins-x-platform repo, but it doesn't seem to be what I am looking for... anybody here in the community got any ideas? I'm familiar with regular jenkins, but trying to get jenkins-x installed is stumping myself and my colleague.

**Comment by jstrachan** [comment]
I'd recommend using the installer - `jx install` or `jx create cluster` to do it for you.
* https://jenkins-x.io/getting-started/install-on-cluster/
* https://jenkins-x.io/getting-started/create-cluster/

you can automate those easily inside Ansible / Terraform.

We don't recommend trying to do all that stuff yourself by hand - its super hard setting up N git repos, git tokens, docker registry tokens, IAM stuff, DNS, ingress etc etc

**Comment by jstrachan** [comment]
see also: https://jenkins-x.io/commands/jx_create_terraform/ and https://www.cloudbees.com/blog/using-jx-create-gitops-managed-jenkins-x-installation-%C2%A0cloudbees-codeship-and-terraform-gke
