### ISSUE TITLE
Can't run in China because gcr.io is blocked

### ISSUE THREAD

**Issue by carlossg** [jenkins-x/jenkins-x-platform#5551]
gcr.io is blocked. Dockerhub is not

```
$ k get pods
NAME                                             READY   STATUS             RESTARTS   AGE
crier-749f96fb4d-hlddq                           0/1     ImagePullBackOff   0          12m
deck-696f77d746-6wlg5                            0/1     ImagePullBackOff   0          12m
deck-696f77d746-rw96p                            0/1     ErrImagePull       0          12m
expose-vvb9s                                     0/1     ImagePullBackOff   0          7m42s
hook-6d9859bb47-9fxlq                            0/1     ImagePullBackOff   0          12m
hook-6d9859bb47-f2q8h                            0/1     ImagePullBackOff   0          12m
horologium-6bc57b5f9-2c9pm                       0/1     ImagePullBackOff   0          12m
jenkins-x-chartmuseum-75d45b6d7f-nhlgx           1/1     Running            0          10m
jenkins-x-controllerbuild-5d957488fc-pb2k5       0/1     ImagePullBackOff   0          10m
jenkins-x-controllerrole-567d98bcdb-vtlj4        1/1     Running            0          10m
jenkins-x-controllerteam-865b78fc69-ck67z        0/1     ErrImagePull       0          10m
jenkins-x-docker-registry-6d555974c7-wrcdq       1/1     Running            0          10m
jenkins-x-heapster-77b5c99cd8-qwm7s              0/2     ImagePullBackOff   0          9m16s
jenkins-x-mongodb-696fdf64fc-nkplf               1/1     Running            1          9m17s
jenkins-x-monocular-api-6b676d869-fc5w9          1/1     Running            2          9m7s
jenkins-x-monocular-prerender-77f6cd8449-rw9lc   1/1     Running            0          9m3s
jenkins-x-monocular-ui-7b98595f74-rcl59          1/1     Running            0          8m58s
jenkins-x-nexus-6ccd45c57c-x92cl                 0/1     ImagePullBackOff   0          8m52s
pipeline-5f85b8df5b-rkszf                        0/1     ImagePullBackOff   0          11m
pipelinerunner-744d857549-fdxgp                  0/1     ImagePullBackOff   0          11m
plank-8849d9d67-4k8dx                            0/1     ImagePullBackOff   0          11m
sinker-85ff54bd9b-js6bx                          0/1     ImagePullBackOff   0          11m
tekton-pipelines-controller-687cfbcc89-fhsr4     0/1     ImagePullBackOff   0          13m
tekton-pipelines-webhook-7fd7f8cdcc-mnxjn        0/1     ImagePullBackOff   0          13m
tide-5f8fb5964c-f6jsr                            0/1     ImagePullBackOff   0          11m
```

**Comment by carlossg** [comment]
Helm charts hosted in google can't be downloaded either

**Comment by zeusro** [comment]
It is blocked by the Chinese gov,not Alibaba

**Comment by caryyu** [comment]
Any solution here to pass this?

**Comment by carlossg** [comment]
I have copied docker images to dockerhub, so you could install using this instructions as long as you use the same version of `jx`

https://gist.github.com/carlossg/aaeef907d59e2c64e6745da532ecd446

**Comment by caryyu** [comment]
@carlossg I think I'm sort of very close to figuring this out by using an accelerating domain `gcr.azk8s.cn` to replace `gcr.io` (see the mapping list below) with `myvalues.yaml` (refering to https://jenkins-x.io/getting-started/config/), But the other some issues I've encountered is not all the image repositories can be passed via this approach, for instance: `gcr.io/jenkinsxio/prow`&`gcr.io/tekton-releases`&`gcr.io/jenkinsxio/builder-maven`, etc ..

| Alternative | Origin |
| ---- | ---- | 
| gcr.azk8s.cn/google_containers | k8s.gcr.io |
| gcr.azk8s.cn | gcr.io |

The most desired expectation for me is how we can have this approach to solve all image downloading issues or In JX command line has an option to cover this.

**Comment by carlossg** [comment]
I didn't know about gcr.azk8s.cn, that simplifies things
Take a look at my values.yaml file here, it should be easy to replace my `csanchez` images with `gcr.azk8s.cn`
https://github.com/carlossg/cloud-environments/blob/alibaba-china/env-alibaba/myvalues.yaml

**Comment by caryyu** [comment]
@carlossg LGTM😄, Your config file is really helpful, i think that will be better If you make some comments on those replaced images, which one matches which original one; because it is not that simple about what you described of replacing the image repository prefix of `csanchez`.

**Comment by zeusro** [comment]
@caryyu dockerhub would be better.We can pull dockerhub‘s images by using     "registry-mirrors"

**Comment by caryyu** [comment]
@zeusro however, the default images are all on the Google cloud, which means, somebody needs to do the copy efforts or there has an automatic synchronization because what @carlossg has done requires us for a specific version of JX so that your installation can be perfectly done, otherwise, the image tags can't correctly match with the latest version of JX

**Comment by carlossg** [comment]
This values.yaml file works now https://github.com/carlossg/jenkins-x-cloud-environments-alibaba-china/blob/master/env-alibaba/myvalues.yaml
