### ISSUE TITLE
[Tekton] PipelineResources duplicated for the same branch

### ISSUE THREAD

**Issue by salaboy** [jenkins-x/jenkins-x-platform#5801]
Every time I trigger the pipeline it create a new pipeline resource instead of reusing the same one for the project+branch.

```
salaboy-conference-sponsors-mas         1d
salaboy-conference-sponsors-mas-6c4ml   23h
salaboy-conference-sponsors-mas-ccqzx   22h
salaboy-conference-sponsors-mas-jqfxb   22h
salaboy-conference-sponsors-mas-mmf9k
```

In order to reproduce just create a project, trigger multiple builds and then do
> jx get pipelineresources 

@abayer ^

**Comment by abayer** [comment]
https://github.com/jenkins-x/jx/issues/4913 replaces this in the right repo. =)
