### ISSUE TITLE
Can you change -Xmx192m t0 -Xmx1024m

### ISSUE THREAD

**Issue by neethualex** [jenkins-x/jenkins-x-platform#6232]
@jstrachan 
Can you change -Xmx192m to -Xmx1024m

I get heap space error while running maven build throught jenkinsx

**Comment by ascheman** [comment]
There is a workaround for that @neethualex: You can just append your settings to the `_JAVA_OPTIONS` environment variable before calling Maven or Gradle or anything else, e.g.,

```shell
_JAVA_OPTIONS="${_JAVA_OPTIONS} -Xmx3096m" mvn clean deploy ...
```

And I guess it is hard to find a setting in the generic builder image which makes everyone happy?
