### ISSUE TITLE
Upgrade Jenkins Helm chart

### ISSUE THREAD

**Issue by vkropotko** [jenkins-x/jenkins-x-platform#6915]
Hi,
Could you please upgrade Jenkins Helm Chart.
There is no way to install custom Jenkins plugins in the current helm chart.
You can add `plugin.txt` with `Master.InstallPlugins` option but these plugins will not be installed due to lack of this https://github.com/helm/charts/blob/master/stable/jenkins/templates/config.yaml#L260.

**Comment by antiqe** [comment]
Is it possible to fix it ? I not find the right repository to opened a PR to fix it by myself but if you point me the right place, i can do it.
