### ISSUE TITLE
[Installer - MacOSX] "make: semver-release-version: Command not found"

### ISSUE THREAD

**Issue by cyrille-leclerc** [jenkins-x/jenkins-x-platform#7]
https://github.com/jenkins-x/jenkins-x-platform/blob/7e1affa1dd728ac0fda8ce7f281254dd6d6b7780/Makefile#L4

```sh
RELEASE_VERSION := $(shell semver-release-version)
```

```
make setup
make: semver-release-version: Command not found
No resources found.
brew install kubernetes-helm
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, caskroom/cask).
==> New Formulae
...
```

**Comment by rawlingsj** [comment]
Did this cause the `make setup` to fail or is it just that it's unnecessary noise in the log?

**Comment by cyrille-leclerc** [comment]
`make setup` did not fail. The running app does not seem to be damaged.

**Comment by rawlingsj** [comment]
ok cool - for now I'm just avoiding the semver command until we move it to the release pipeline https://github.com/jenkins-x/jenkins-x-platform/commit/eeae374ce611234d98db289e1ff0c400abd5efec
