### ISSUE TITLE
Need help for install jenkinsx on Alibaba Cloud Container Service 

### ISSUE THREAD

**Issue by qinyujia** [jenkins-x/jenkins-x-platform#953]
hi, I am trying to install jenkins-x on Alibaba Cloud Container Service K8s cluster. Since the Cloud Provider does not contain "Alibaba Cloud", so I chose "Kubernetes".

But I found that I need to set STORAGECLASS for pvc. 

So I download file https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml and saved as /root/.jx/cloud-environments/env-kubernetes/myvalues.yaml. Then I added "StorageClass: "alicloud-disk-available" " at three points of this file(docker-registry, chartmuseum and jenkins):
...
docker-registry:
  service:
    annotations:
      fabric8.io/expose: "true"
  persistence:
    StorageClass: "alicloud-disk-available"
    accessMode: 'ReadWriteOnce'
    enabled: true
    size: 100Gi
...
chartmuseum:
  service:
    annotations:
      fabric8.io/expose: "true"
  persistence:
    StorageClass: "alicloud-disk-available"
    Enabled: true
    AccessMode: ReadWriteOnce
    Size: 20Gi
...
jenkins...
  Persistence:
    Enabled: true
    ## A manually managed Persistent Volume and Claim
    ## Requires Persistence.Enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    # ExistingClaim:
  
    ## jenkins data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # StorageClass: "-"
    StorageClass: "alicloud-disk-available"
    AccessMode: ReadWriteOnce
    Size: 30Gi
...

Next , jx install with /root/.jx/cloud-environments/env-kubernetes..
when I typied kubectl get pvc, the logs as below:
[root@iZj6capa0vx4v3ocm7p3tqZ env-kubernetes]# kubectl get pvc
NAME                        STATUS    VOLUME                   CAPACITY   ACCESS MODES   STORAGECLASS              AGE
jenkins                     Bound     d-j6c2o1y9owf0v7mhb14c   30Gi       RWO            alicloud-disk-available   11m
jenkins-x-chartmuseum       Bound     d-j6c1ugw2oekw1tk8hd67   20Gi       RWO            alicloud-disk-available   11m
jenkins-x-docker-registry   Bound     d-j6c2o1y9owf0v7mhb14d   100Gi      RWO            alicloud-disk-available   11m
jenkins-x-mongodb           Pending                                                                                11m
jenkins-x-nexus             Pending

So my question is how to set STORAGECLASS for jenkins-x-mongodb and jenkins-x-nexus? 
Thank you.

**Comment by qinyujia** [comment]
here is more detailed logs:

[root@iZj6capa0vx4v3ocm7p3tqZ env-kubernetes]# helm status jenkins-x
LAST DEPLOYED: Thu Apr 26 15:58:04 2018
NAMESPACE: jx
STATUS: DEPLOYED

RESOURCES:
==> v1/Pod(related)
NAME                                           READY  STATUS            RESTARTS  AGE
jenkins-x-chartmuseum-7b95b777b-ld5fg          1/1    Running           0         14m
jenkins-x-docker-registry-6786bc55b7-mqmcq     1/1    Running           0         14m
jenkins-x-heapster-96bd95dcf-vrnkj             2/2    Running           0         14m
jenkins-7bb87f4445-4mxlb                       1/1    Running           0         14m
jenkins-x-mongodb-6c84f866dc-hwsm5             0/1    Pending           0         14m
jenkins-x-monocular-api-d8995679b-pndcs        0/1    CrashLoopBackOff  7         14m
jenkins-x-monocular-prerender-6d8897856-5bd8g  1/1    Running           0         14m
jenkins-x-monocular-ui-55bd48f76-l44pj         1/1    Running           0         14m
jenkins-x-nexus-57866468c9-vwqvd               0/1    Pending           0         14m
pipelinecontroller-5dbc96bbd4-jjhn9            1/1    Running           0         14m

==> v1/Secret
NAME                              TYPE    DATA  AGE
jenkins-x-chartmuseum             Opaque  2     14m
jenkins-x-docker-registry-secret  Opaque  1     14m
jenkins                           Opaque  2     14m
jenkins-x-mongodb                 Opaque  2     14m
nexus                             Opaque  1     14m
jenkins-docker-cfg                Opaque  1     14m
jenkins-git-credentials           Opaque  1     14m
jenkins-hub-api-token             Opaque  1     14m
jenkins-git-ssh                   Opaque  2     14m
jx-basic-auth                     Opaque  1     14m
jenkins-release-gpg               Opaque  4     14m
jenkins-maven-settings            Opaque  1     14m
jenkins-npm-token                 Opaque  1     14m
jenkins-ssh-config                Opaque  1     14m

==> v1/ConfigMap
NAME                              DATA  AGE
jenkins-x-docker-registry-config  1     14m
exposecontroller                  1     14m
jenkins                           6     14m
jenkins-x-git-kinds               2     14m
jenkins-tests                     1     14m
jenkins-x-monocular-api-config    1     14m
jenkins-x-monocular-ui-config     1     14m
jenkins-x-monocular-ui-vhost      1     14m

==> v1/PersistentVolumeClaim
NAME                       STATUS   VOLUME                  CAPACITY  ACCESS MODES  STORAGECLASS             AGE
jenkins-x-chartmuseum      Bound    d-j6c1ugw2oekw1tk8hd67  20Gi      RWO           alicloud-disk-available  14m
jenkins-x-docker-registry  Bound    d-j6c2o1y9owf0v7mhb14d  100Gi     RWO           alicloud-disk-available  14m
jenkins                    Bound    d-j6c2o1y9owf0v7mhb14c  30Gi      RWO           alicloud-disk-available  14m
jenkins-x-mongodb          Pending  14m
jenkins-x-nexus            Pending  14m

==> v1/Role
NAME     AGE
cleanup  14m
expose   14m

==> v1/Service
NAME                           TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)    AGE
jenkins-x-chartmuseum          ClusterIP  172.19.7.91    <none>       8080/TCP   14m
jenkins-x-docker-registry      ClusterIP  172.19.12.14   <none>       5000/TCP   14m
heapster                       ClusterIP  172.19.15.207  <none>       8082/TCP   14m
jenkins-agent                  ClusterIP  172.19.7.174   <none>       50000/TCP  14m
jenkins                        ClusterIP  172.19.15.156  <none>       8080/TCP   14m
jenkins-x-mongodb              ClusterIP  172.19.5.85    <none>       27017/TCP  14m
jenkins-x-monocular-api        ClusterIP  172.19.7.163   <none>       80/TCP     14m
jenkins-x-monocular-prerender  ClusterIP  172.19.13.80   <none>       80/TCP     14m
jenkins-x-monocular-ui         ClusterIP  172.19.15.194  <none>       80/TCP     14m
nexus                          ClusterIP  172.19.12.32   <none>       80/TCP     14m

==> v1beta1/Deployment
NAME                           DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
jenkins-x-chartmuseum          1        1        1           1          14m
jenkins-x-docker-registry      1        1        1           1          14m
jenkins-x-heapster             1        1        1           1          14m
jenkins                        1        1        1           1          14m
jenkins-x-mongodb              1        1        1           0          14m
jenkins-x-monocular-api        1        1        1           0          14m
jenkins-x-monocular-prerender  1        1        1           1          14m
jenkins-x-monocular-ui         1        1        1           1          14m
jenkins-x-nexus                1        1        1           0          14m
pipelinecontroller             1        1        1           1          14m

==> v1beta1/CustomResourceDefinition
NAME                  AGE
pipelines.jenkins.io  14m
runs.jenkins.io       14m

==> v1/ServiceAccount
NAME                SECRETS  AGE
cleanup             1        14m
expose              1        14m
jenkins             1        14m
pipelinecontroller  1        14m

==> v1beta1/ClusterRoleBinding
NAME                  AGE
jenkins-role-binding  14m

==> v1/RoleBinding
NAME     AGE
cleanup  14m
expose   14m

**Comment by qinyujia** [comment]
any commdents?

**Comment by liuxiaopiao** [comment]
Met nearly the same problem for another cloud vendor

**Comment by liuxiaopiao** [comment]
@qinyujia , have you figured out the problem? if that, can you share the notes? Thanks a lot

**Comment by qinyujia** [comment]
@liuxiaopiao The fastest way to get help with Jenkins-X is on the Slack channel: http://slack.k8s.io/ in the https://kubernetes.slack.com/messages/C9MBGQJRH channel

**Comment by zetaron** [comment]
@qinyujia I've had similar issues with IBM Cloud.

After some digging, I found out that `mongodb` is a dependency of `monocular`.

Below I've put the configuration I used for IBM Cloud which I've into the `~/.jx/cloud-environments/env-ibm/myvalues.yaml` file and used `jx install --provider=ibm` to install it:
```yaml
# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml
docker-registry:
  persistence:
    enabled: true
    storageClass: "default"
chartmuseum:
  persistence:
    enabled: true
    StorageClass: "default"
jenkins:
  Persistence:
    Enabled: true
    StorageClass: "default"
nexus:
  persistence:
    enabled: true
    storageClass: "default"
monocular:
  mongodb:
    persistence:
      enabled: true
      storageClass: "default"
```

I hope this helps you and maybe others, struggling with a non OOTB experience regarding PVCs.

**Comment by qinyujia** [comment]
@zetaron thanks for your wonderful advice, i have sorted out the materials to repo https://github.com/qinyujia/cloud-environments.git. Just place it to path ~/.jx/cloud-environments, then try jx install --provider=kubernetes.

**Comment by carlossg** [comment]
but there are other issues with alibaba that I'm documenting
